feature/VueJS-2: was done 2 stage
itbgtk09/ToDoVueJS pull request #2
Opened 2021-06-15 21:41 UTC by itbgtk09

2021-06-17 14:32 UTC, DenisKalyanov requested changes

2021-06-17 14:32 UTC, DenisKalyanov commented on src/components/ToDoList.vue
> +$checkboxColor: rgb(54, 112, 199);
Если ты уже выносишь в переменные цвета, то создай для них отдельный документ, где будут они все.

2021-06-17 14:32 UTC, DenisKalyanov commented on tests/unit/example.spec.js
> +import HelloWorld from '@/components/HelloWorld.vue'
Ты тут типо тесты оставил, но сейчас у тебя нет такого компонента.

2021-06-17 14:37 UTC, DenisKalyanov requested changes

2021-06-17 14:37 UTC, DenisKalyanov commented on src/components/ToDoList.vue
> +        <div class="task-text">text1</div>
тег label строчный, а ты в него вкладываешь блочный.

2021-06-17 14:37 UTC, DenisKalyanov commented on src/components/ToDoComponent.vue
> +    color: white;
цвета все заменяем переменными, а переменные выносим в отдельный файл

2021-06-17 14:38 UTC, DenisKalyanov requested changes

2021-06-17 14:38 UTC, DenisKalyanov commented on src/components/ToDoComponent.vue
> +@media (max-width: 768px) {
выноси  breckpoints в отдельный файл и используй их как переменные.

2021-06-18 11:06 UTC, itbgtk09 commented on src/components/ToDoComponent.vue
> +@media (max-width: 768px) {
создать media.scss и импортировать его в компонент?

2021-06-18 19:56 UTC, Andrej-Novik commented on src/styles/reset.scss
> +html, body, div, span, h1, h2, h3, h4, h5, h6, ol, ul, p, nav, section, audio, video {
Вся папочка styles должна находиться в папке assets

2021-06-18 19:56 UTC, Andrej-Novik commented on src/components/ToDoComponent.vue
> +<template>
Избавляемся от BEMа, в компонентной верстке в нем нет необходимости, и можешь начинать разбивать на компоненты. При разбиении попробуй использовать atomic design(почитай сам, я на созвоне еще поясню)

2021-06-18 19:56 UTC, Andrej-Novik commented on src/components/ToDoComponent.vue
> +    <div class="to-do__buttons">
не знаю, был ли у вас макет, но я скину пример, может тебе больше понравится, и как по мне он получше будет. Вопрос не в дизайне, а в расположении логических элементов на странице, у тебя вчера смотрел - все в куче было.

2021-06-18 19:56 UTC, Andrej-Novik commented on src/components/ToDoComponent.vue
> +<style lang="scss">
Скорее всего это будет на следующем этапе, но используй модульный scss(если будут вопросы - расскажу)

2021-06-18 19:56 UTC, Andrej-Novik commented on src/components/ToDoComponent.vue
> +@import '../styles/variables.scss';
Используй абсалютный импорт (@import "@/assets/styles/FileName.scss")

2021-06-18 19:56 UTC, Andrej-Novik commented on src/components/ToDoComponent.vue
> +  width: $containerWidth;
Круто, что начал использовать все прелести препроцессоров, думаю сам понимаешь, насколько это может упрощать работу.

2021-06-21 18:47 UTC, Andrej-Novik commented on src/components/atoms/Button.vue
> +    callback: Function
убираем функцию, она не нужна

2021-06-21 18:47 UTC, Andrej-Novik commented on src/components/atoms/Task.vue
> +    <label :class="$style.label" :id="id">
тут id не нужен

2021-06-21 18:47 UTC, Andrej-Novik commented on src/components/atoms/Task.vue
> +  <div :class="$style.task" :data-taskId="taskId">
data-taskId убираем

2021-06-21 18:47 UTC, Andrej-Novik commented on src/components/atoms/Task.vue
> +    id: Number,
taskId не нужен

2021-06-21 18:47 UTC, Andrej-Novik commented on src/components/moleculs/Tasks.vue
> +      :key="[note.text,note.id ,index]"
в ключе нужно только note.id

2021-06-21 18:47 UTC, Andrej-Novik commented on src/components/moleculs/Tasks.vue
> +      v-for="(note, index) in notes"
index не нужен

2021-06-21 18:47 UTC, Andrej-Novik commented on src/components/moleculs/Tasks.vue
> +      :taskId="index + 1"
taskId не нужен

2021-06-21 18:47 UTC, Andrej-Novik commented on src/components/moleculs/Tasks.vue
> +        { id: 1, text: 'Buy bread', isCompleted: true },
id у задач разные должны быть, можно пока 1,2,3 поставить

2021-06-21 18:47 UTC, Andrej-Novik commented on src/store/index.js
> +import { createStore } from 'vuex'
вот уже тут будет наша логика, начинай читать про vuex

2021-06-23 17:15 UTC, merged